;; og:preserve-this bring-up: remaining .o entries converted to .go raw copies (brdroom recipe)
("JGA.DGO"
 ("tpage-649.go"
  "tpage-962.go"
  "tpage-650.go"
  "tpage-652.go"
  "jungle-debris-jar-a-ag.go"
  "jungle-debris-jar-b-ag.go"
  "jungle-debris-ag.go"
  "jungle-clay-jar-b-ag.go"
  "jungle-clay-jar-a-ag.go"
  "jungle-tree-root-large-b-ag.go"
  "jungle-tree-root-large-a-ag.go"
  "junglea-vis.go"
 ))
