;; og:preserve-this bring-up: remaining .o entries converted to .go raw copies (brdroom recipe)
("JGE.DGO"
 ("tpage-640.go"
  "tpage-1050.go"
  "tpage-967.go"
  "tpage-966.go"
  "jungle-debris-jar-a-ag.go"
  "jungle-debris-jar-b-ag.go"
  "jungle-debris-ag.go"
  "jungle-clay-jar-b-ag.go"
  "jungle-clay-jar-a-ag.go"
  "jungle-tree-root-large-b-ag.go"
  "jungle-tree-root-large-a-ag.go"
  "junglee-vis.go"
 ))
